name: intralink
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.4.0
  # english_words: ^3.1.5
  # audioplayers: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  geolocator: ^6.2.1
  image_picker: ^0.8.0+1
  smart_select: ^4.3.2
  flutter_multiselect: ^0.0.1
  multi_select_flutter: ^2.1.0
  circular_profile_avatar: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/
    - Images/